export const WS_CLIENT_EVENTS = {
  SEND_PRIVATE_MESSAGE: 'SEND_PRIVATE_MESSAGE',
  SEND_GROUP_MESSAGE: 'SEND_GROUP_MESSAGE',
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  MESSAGE_READ: 'MESSAGE_READ',
  GROUP_INVITE_MEMBER: 'GROUP_INVITE_MEMBER',
  GROUP_INVITATION_ACCEPT: 'GROUP_INVITATION_ACCEPT',
  GROUP_INVITATION_REJECT: 'GROUP_INVITATION_REJECT',
} as const;

export const WS_SERVER_EVENTS = {
  MESSAGE_SENT: 'MESSAGE_SENT',
  NEW_MESSAGE: 'NEW_MESSAGE',
  MESSAGE_STATUS_UPDATED: 'MESSAGE_STATUS_UPDATED',
  GROUP_INVITATION: 'GROUP_INVITATION',
  GROUP_MEMBER_JOINED: 'GROUP_MEMBER_JOINED',
  GROUP_MEMBER_LEFT: 'GROUP_MEMBER_LEFT',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',
  GROUP_OWNER_CHANGED: 'GROUP_OWNER_CHANGED',
  GROUP_DELETED: 'GROUP_DELETED',
  ERROR: 'ERROR',
} as const;

export type WsClientEvent = (typeof WS_CLIENT_EVENTS)[keyof typeof WS_CLIENT_EVENTS];
export type WsServerEvent = (typeof WS_SERVER_EVENTS)[keyof typeof WS_SERVER_EVENTS];
