export const WS_CLIENT_EVENTS = {
  AUTH_TOKEN_SENT: 'AUTH_TOKEN_SENT',
  SEND_PRIVATE_MESSAGE: 'SEND_PRIVATE_MESSAGE',
  SEND_GROUP_MESSAGE: 'SEND_GROUP_MESSAGE',
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  MESSAGE_READ: 'MESSAGE_READ',
  GROUP_INVITE_MEMBER: 'GROUP_INVITE_MEMBER',
  GROUP_INVITATION_ACCEPT: 'GROUP_INVITATION_ACCEPT',
  GROUP_INVITATION_REJECT: 'GROUP_INVITATION_REJECT',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
} as const;

export const WS_SERVER_EVENTS = {
  REQUEST_AUTH_TOKEN: 'REQUEST_AUTH_TOKEN',
  MESSAGE_SENT: 'MESSAGE_SENT',
  NEW_MESSAGE: 'NEW_MESSAGE',
  MESSAGE_STATUS_UPDATED: 'MESSAGE_STATUS_UPDATED',
  GROUP_INVITATION: 'GROUP_INVITATION',
  GROUP_MEMBER_JOINED: 'GROUP_MEMBER_JOINED',
  GROUP_MEMBER_LEFT: 'GROUP_MEMBER_LEFT',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',
  GROUP_OWNER_CHANGED: 'GROUP_OWNER_CHANGED',
  GROUP_DELETED: 'GROUP_DELETED',
  PRESENCE_ONLINE: 'PRESENCE_ONLINE',
  PRESENCE_OFFLINE: 'PRESENCE_OFFLINE',
  TYPING_STARTED: 'TYPING_STARTED',
  TYPING_STOPPED: 'TYPING_STOPPED',
  ERROR: 'ERROR',
} as const;

export type WsClientEvent = (typeof WS_CLIENT_EVENTS)[keyof typeof WS_CLIENT_EVENTS];
export type WsServerEvent = (typeof WS_SERVER_EVENTS)[keyof typeof WS_SERVER_EVENTS];
